version: '2'
services:
  aliveservice-app:
    image: aliveservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://aliveservice-mysql:3306/aliveservice?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - JHIPSTER_REGISTRY_PASSWORD=${JHIPSTER_REGISTRY_PASSWORD}
      - BASE64_SECRET=${BASE64_SECRET}
      - VIRTUAL_HOST=alive-service.7lofficial.de
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=alive-service.7lofficial.de
      - LETSENCRYPT_EMAIL=server-administration@7lofficial.de
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - nginx-proxy_default
      - default
  aliveservice-mysql:
    extends:
      file: mysql.yml
      service: aliveservice-mysql
  jhipster-registry:
    extends:
      file: jhipster-registry-prod.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/svenleonhard/server-config-public/
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=jhipster-registry-services
networks:
  nginx-proxy_default:
    external: true
