version: '2'
services:
  aliveservice-app:
    image: 7lofficial/aliveservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://aliveservice-mysql:3306/aliveservice?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=120 # gives time for other services to boot before the application
      - JHIPSTER_REGISTRY_PASSWORD=admin1
      - BASE64_SECRET=o0rVA9ESSjtL3TxbYxN49wevBY/Z2ETlswu1Q8gQxoMzM4zzlQC0fyTwC3EsPtn4lU7eJEJrbKRQvCyoWWYnVg==
      - VIRTUAL_HOST=alive-service.7lofficial.de
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=alive-service.7lofficial.de
      - LETSENCRYPT_EMAIL=server-administration@7lofficial.de
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - nginx-proxy_default
      - default
  aliveservice-mysql:
    extends:
      file: mysql.yml
      service: aliveservice-mysql
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.3.0
    volumes:
      - ./central-server-config:/central-config
      # When run with the "dev" Spring profile, the JHipster Registry will
      # read the config from the local filesystem (central-server-config directory)
      # When run with the "prod" Spring profile, it will read the configuration from a Git repository
      # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - nginx-proxy_default
      - default
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_SECURITY_USER_PASSWORD=admin1
      - JHIPSTER_REGISTRY_PASSWORD=admin1
      - VIRTUAL_HOST=service-registry.7lofficial.de
      - VIRTUAL_PORT=8761
      - LETSENCRYPT_HOST=service-registry.7lofficial.de
      - LETSENCRYPT_EMAIL=server-administration@7lofficial.de
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
    ports:
      - 8761:8761
networks:
  nginx-proxy_default:
    external: true
