# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: GET, PUT, POST, DELETE, OPTIONS
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
